import { db } from '@k39/database'

const days: AdventDay[] = [
  {
    dayNumber: 1,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'story',
  },
  {
    dayNumber: 2,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'share',
  },
  {
    dayNumber: 3,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'riddle',
  },
  {
    dayNumber: 4,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'light',
  },
  {
    dayNumber: 5,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'story',
  },
  {
    dayNumber: 6,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'message',
  },
  {
    dayNumber: 7,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'community-trees',
  },
  {
    dayNumber: 8,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'message',
  },
  {
    dayNumber: 9,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'story',
  },
  {
    dayNumber: 10,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'fortune-cookie',
  },
  {
    dayNumber: 11,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'deer',
  },
  {
    dayNumber: 12,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'story',
  },
  {
    dayNumber: 13,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'negativity',
  },
  {
    dayNumber: 14,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'present-idea',
  },
  {
    dayNumber: 15,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'story',
  },
  {
    dayNumber: 16,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'association-with-food',
  },
  {
    dayNumber: 17,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'polar-bear',
  },
  {
    dayNumber: 18,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'community-wish',
  },
  {
    dayNumber: 19,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'story',
  },
  {
    dayNumber: 20,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'message',
  },
  {
    dayNumber: 21,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'community-goals',
  },
  {
    dayNumber: 22,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'favorite-music',
  },
  {
    dayNumber: 23,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'message',
  },
  {
    dayNumber: 24,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'favorite-film',
  },
  {
    dayNumber: 25,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'story',
  },
  {
    dayNumber: 26,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'message',
  },
  {
    dayNumber: 27,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'companion',
  },
  {
    dayNumber: 28,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'message',
  },
  {
    dayNumber: 29,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'penguin',
  },
  {
    dayNumber: 30,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'message',
  },
  {
    dayNumber: 31,
    isDayOver: false,
    isOpened: false,
    canOpen: false,
    isCompleted: false,
    type: 'community-food-table',
  },
]

export default defineEventHandler(async (event) => {
  try {
    const dayNow = 0

    const userInDB = await db.user.find(event.context?.user?.id)
    if (!userInDB) {
      // Return base objects
      return days.map((day) => ({
        ...day,
        isDayOver: dayNow >= day.dayNumber,
        canOpen: dayNow >= day.dayNumber,
        isOpened: false,
      }))
    }

    // Return days with user data
    return days.map((day) => ({
      ...day,
      isDayOver: dayNow >= day.dayNumber,
      isOpened: dayNow >= day.dayNumber,
    }))
  } catch (error) {
    throw errorResolver(error)
  }
})
